apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: default-route-openshift-image-registry.apps.ocp.lab.supporting.devmandiri.co.id/catalog-backend/skafoldd
      jib: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s/openshift.yaml
    - k8s/service.yaml
