apiVersion: apps/v1
kind: Deployment
metadata:
  name: skafoldd
spec:
  selector:
    matchLabels:
      app: skafoldd
  replicas: 1
  template:
    metadata:
      labels:
        app: skafoldd
    spec:
      containers:
        - name: skafoldd
          image: default-route-openshift-image-registry.apps.ocp.lab.supporting.devmandiri.co.id/catalog-backend/skafoldd
          ports:
            - containerPort: 8080
